### ISSUE TITLE
WL is not defined  error

### ISSUE THREAD

**Issue by hnguyenec** [Vivify-Ideas/angular-one-drive-picker#1]
from my understanding, WL is used for oauth authentication
But where should I get this file

**Comment by nikolasp** [comment]
Hi. You need to include OneDrive reference to SDK before call to this directive.
`<script type="text/javascript" src="https://js.live.net/v5.0/OneDrive.js" id="onedrive-js" client-id="APP_ID"></script>`

If you need only Live SDK javascript library(WL) more info with links to .js files you can find on this page. - https://msdn.microsoft.com/en-us/library/office/hh550837.aspx
